blank_issues_enabled: false
contact_links:
  - name: Github Discussions
    url: https://github.com/chmmou/olbaflinx/discussions
    about: Start a discussion about the project, compiling, or any other general question.