name: Ubuntu (CTests)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out the code
        uses: actions/checkout@v2

      - name: Install dependencies
        id: vars
        run: |
          echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
          sudo apt-get -qq update
          sudo apt-get install -y -qq \
            libgcrypt20-dev \
            libgcrypt20 \
            libgpg-error-dev \
            libgpg-error0 \
            libgnutls28-dev \
            libgnutls30 \
            libgnutls-openssl27 \
            libxmlsec1-gnutls \
            libxmlsec1-dev \
            libxmlsec1-gcrypt \
            libxmlsec1-nss \
            libxmlsec1-openssl \
            libxmlsec1 \
            xmlsec1 \
            libgl1-mesa-dev \
            libxkbcommon-x11-0 \
            libc6-i386 \
            build-essential \
            libgl1-mesa-dev \
            mesa-common-dev \
            libgles2-mesa-dev \
            libxkbcommon-x11-0 \
            libxcb-icccm4-dev \
            libxcb-xinerama0 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-* \
            fakeroot \
            git \
            cmake
          sudo apt-get remove -y -qq gcc g++
          sudo apt install -y -qq gcc-9 g++-9
          sudo ln -s /usr/bin/g++-9 /usr/bin/g++
          sudo ln -s /usr/bin/gcc-9 /usr/bin/gcc
          sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-focal
          sudo apt-get -qq update
          sudo apt install -y -qq qt5153d \
            qt515base \
            qt515charts-no-lgpl \
            qt515connectivity \
            qt515datavis3d-no-lgpl \
            qt515declarative \
            qt515doc \
            qt515gamepad \
            qt515graphicaleffects \
            qt515imageformats \
            qt515location \
            qt515lottie-no-lgpl \
            qt515multimedia \
            qt515networkauth-no-lgpl \
            qt515opcua \
            qt515quick3d-no-lgpl \
            qt515quickcontrols \
            qt515quickcontrols2 \
            qt515quicktimeline-no-lgpl \
            qt515remoteobjects \
            qt515script \
            qt515scxml \
            qt515sensors \
            qt515serialbus \
            qt515serialport \
            qt515speech \
            qt515svg \
            qt515tools \
            qt515translations \
            qt515wayland \
            qt515webchannel \
            qt515webengine \
            qt515webglplugin-no-lgpl \
            qt515websockets \
            qt515x11extras \
            qt515xmlpatterns
      - name: Setup additional dependencies
        id: aqbanking
        run: |
          source /opt/qt515/bin/qt515-env.sh
          echo $PATH
          echo $LD_LIBRARY_PATH
          qmake -v
