name: Ubuntu (CTests)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out the code
        uses: actions/checkout@v2

      - name: Install dependencies
        id: vars
        run: |
          echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
          sudo apt-get -qq update
          sudo apt-get install -y -qq \
            libgcrypt20-dev \
            libgcrypt20 \
            libgpg-error-dev \
            libgpg-error0 \
            libgnutls28-dev \
            libgnutls30 \
            libgnutls-openssl27 \
            libxmlsec1-gnutls \
            libxmlsec1-dev \
            libxmlsec1-gcrypt \
            libxmlsec1-nss \
            libxmlsec1-openssl \
            libxmlsec1 \
            xmlsec1 \
            libgl1-mesa-dev \
            libxkbcommon-x11-0 \
            libc6-i386 \
            build-essential \
            libgl1-mesa-dev \
            mesa-common-dev \
            libgles2-mesa-dev \
            libxkbcommon-x11-0 \
            libxcb-icccm4-dev \
            libxcb-xinerama0 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-* \
            fakeroot \
            git \
            cmake
          sudo apt-get remove -y -qq gcc g++
          sudo apt install -y -qq gcc-9 g++-9
          sudo ln -s /usr/bin/g++-9 /usr/bin/g++
          sudo ln -s /usr/bin/gcc-9 /usr/bin/gcc

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        timeout-minutes: 10
        with:
          version: 5.15.2
          target: desktop
          host: linux
          install-deps: true
          modules: 'qtcharts, qtdatavis3d, qtpurchasing, qtvirtualkeyboard, qtwebengine, qtnetworkauth, qtwebglplugin, qtscript, debug_info'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Cache additional dependencies
        id: cache-additional-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.additional-dependencies
          key: ${{ runner.os }}-additional-dependencies-cache

      - name: Installing additional dependencies
        if: steps.cache-additional-dependencies.outputs.cache-hit != 'true'
        run: |
          wget -c "https://www.aquamaniac.de/rdm/attachments/download/390/gwenhywfar-5.7.3.tar.gz"
          tar -xzf gwenhywfar-5.7.3.tar.gz
          cd gwenhywfar-5.7.3
          ./configure --prefix=$HOME/.additional-dependencies --with-guis="qt5"
          make -j$(nproc) all
          make install
          rm -rf gwenhywfar-5.7.3.tar.gz gwenhywfar-5.7.3
          export PATH="$PATH:~/.additional-dependencies/bin"
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:~/.additional-dependencies/lib"
          wget -c "https://www.aquamaniac.de/rdm/attachments/download/386/aqbanking-6.3.2.tar.gz"
          tar -xzf aqbanking-6.3.2.tar.gz
          cd aqbanking-6.3.2
          ./configure --prefix=$HOME/.additional-dependencies
          make typedefs
          make types
          make -j$(nproc) all
          make install
          rm -rf aqbanking-6.3.2.tar.gz aqbanking-6.3.2
          ls -lvah ~/.additional-dependencies/*

      - name: Setup additional dependencies
        if: steps.cache-additional-dependencies.outputs.cache-hit == 'true'
        run:
          export PATH="$PATH:$HOME/.additional-dependencies/bin"
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/.additional-dependencies/lib"
          aqhbci-tool4 versions
